### ISSUE TITLE
Drop classnames dependency

### ISSUE THREAD

**Issue by bfred-it** [vadimdemedes/dom-chef#15]
Should [`classnames`](https://github.com/JedWatson/classnames) really be part of this package? If dom-chef is meant as the plain-dom equivalent of react-dom, then maybe `classnames` should be a user dependency, like it is for React users:

https://github.com/JedWatson/classnames#usage-with-reactjs

**Comment by vadimdemedes** [comment]
I'm open to removing it. Since dom-chef doesn't really have React-like components, developer can use classnames themselves if they need to.

**Comment by bfred-it** [comment]
I'll send a PR after https://github.com/vadimdemedes/dom-chef/pull/14 is in
