### ISSUE TITLE
Autoprefix styles

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/dom-chef#2]
Would be cool to use [inline-style-prefixer](https://github.com/rofrischmann/inline-style-prefixer/) to autoprefix `style` props.

**Comment by bfred-it** [comment]
Style shouldn't be in the JS in the first place. It might make sense when the JSX is dynamic but not when it's static. Plus it's not a very small dependency: 70KB unminified

**Comment by vadimdemedes** [comment]
Now that I think of it, it might be an over bundling it with features. Let's postpone it and see if other people have different thoughts.

**Comment by mDibyo** [comment]
Agree with @bfred-it. One thing worth considering might be creating automatic classes for elements and generating css placed inside style tags in the head.

**Comment by vadimdemedes** [comment]
That's definitely out of scope of `dom-chef` and is a job for libs like `glamor`.
