### ISSUE TITLE
`CSSStyleDeclaration.setProperty()` doesn't seem to work consistently

### ISSUE THREAD

**Issue by reyronald** [vadimdemedes/dom-chef#23]
Hello! First of all, thank you for creating and maintaining this wonderful package! Now on to the problem..

This is interesting because this is an issue that I've encountered only in a browser environment. As far as I have tested, it is not reproduce-able in NodeJs with `jsdom`. The thing is, `CSSStyleDeclaration.setProperty()` doesn't always work apparently?

In the Chrome Dev Tools (I used Version 66.0.3359.139 (Official Build) (64-bit) on Windows), run:

```js
const label = document.createElement('label')
label.style.setProperty('fontSize', '12px')
label.style.fontSize // will output "", should output "12px"
```

![image](https://user-images.githubusercontent.com/7514993/40069609-d9156f62-5839-11e8-86e8-eb2ff7cbaca7.png)

This is annoying because for some particular CSS properties I am forced to set the style manually without using `dom-chef`. I've read the documentation on `.setProperty` and I can't seem to find any warning of reference that this may happen. I find it specially strange because doing `label.style['fontSize'] = "12px"` will actually work! So I'm inclined to think that this is a bug on the browser implementation of `setProperty` itself.

What do you think? Do you have any clue on why this might be happening? Would it be possible to change `dom-chef`'s implementation to use `style.cssPropertyName = 'value';` instead of `setProperty`? Am I missing something?

```diff
const setCSSProps = (el, style) => {
  Object
    .keys(style)
    .forEach(name => {
      let value = style[name];

      if (typeof value === 'number' && !IS_NON_DIMENSIONAL.test(name)) {
        value += 'px';
      }

-      el.style.setProperty(name, value);
+      el.style[name] = value;
    });
};
```

**Comment by bfred-it** [comment]
I think you’re right. `setProperty` accepts `dashed-names` while JSX works with js properties directly, so your diff looks right. PR welcome, possibly with a failing test for the current implementation. 🙂

**Comment by bfred-it** [comment]
Then a successful test would be ok and perhaps an issue can be opened/found on jsdom

**Comment by reyronald** [comment]
Agreed, I'll open the issue in `jsdom` and reference this one.
