### ISSUE TITLE
Full SVG support

### ISSUE THREAD

**Issue by bfred-it** [vadimdemedes/dom-chef#5]
The list of SVG tags is incomplete, by looking at this one: https://github.com/wooorm/svg-tag-names/blob/master/index.json

In there you can also see regular HTML tag names so it's not as easy as requiring that module. 

This uncovers an issue: all the tags in `<svg><iframe></iframe></svg>` should be created with the SVG namespace, that's what the browser does:

<img width="396" alt="iframe's namespace === SVG" src="https://user-images.githubusercontent.com/1402241/27766634-ba7afd4e-5f09-11e7-9afc-11d4936defdf.png">

The only way to do that is to also look for `<svg>` and `<foreignElement>` into the parents.

**Comment by vadimdemedes** [comment]
> This uncovers an issue: all the tags in <svg><iframe></iframe></svg> should be created with the SVG namespace

Thanks for bringing this up!

The problem is `h` is invoked for the most nested elements first, going from the bottom of the tree upwards. That's why we can't do what Preact does, encounter `<svg>` element and enable `isSVG`, which would use SVG namespace for all children.

Not sure right now how to work around this.

**Comment by vadimdemedes** [comment]
Until there's a solution, `dom-chef` could use `svg-tag-names` and just exclude tags that are also html tags, like `iframe` and `a`. It wouldn't count as full SVG support, but still better than nothing.

**Comment by vadimdemedes** [comment]
Added more tags using `svg-tag-names` module via https://github.com/vadimdemedes/dom-chef/commit/e2f07aedcff13b491fba3b2dd038add81aaf030f.

**Comment by pygy** [comment]
A solution would to have `h` create a vDOM tree as an IR, with a wrapper function called to materialize the DOM.

```JS
const el = domify(<svg><iframe></iframe></svg>);
```

where `domify()` propagates the NS from the root to the children.

**Comment by bfred-it** [comment]
I don't think this can be further resolved and probably it's fine. `<iframe>` works even without the SVG namespace.

Because `babel-plugin-transform-react-jsx` creates nested calls, `h('iframe')` won't know it's a child of `h('svg')` until the latter is created, and we can't safely correct the NS of the iframe once that happens.

The only way to support this would be by changing the babel transform to something that can be parsed at once, like [JSX-IR](https://github.com/OpenJSX/babel-plugin-jsx#example-of-output), but really at that point it's best to just go with https://github.com/vadimdemedes/dom-chef/issues/7#issuecomment-313666029

React either ignores this issue or is able to _correct the NS_ before actually generating the dom because it has total control over it.
