### ISSUE TITLE
Add support for dashed event types via `on` attributes

### ISSUE THREAD

**Issue by fregante** [vadimdemedes/dom-chef#52]
It looks like all default event names are lowercase and none of them have dashes: https://developer.mozilla.org/en-US/docs/Web/Events

I think there's an opportunity to add support for dashed event types via camelCased attributes:

```js
// https://github.com/github/remote-input-element#events
<remote-input onRemoteInputSuccess={console.log} />
```

Currently this is converted to `addEventListener('remoteinputsuccess')` but I think it's worth changing it to `addEventListener('remote-input-success')`

---

This would be a breaking change since anyone using something like `<video onLoadStart={...}>`

That [appears](https://medium.com/frontend-digest/responsive-and-progressive-video-loading-in-react-e8753315af51) to be how React people write those events as well, so perhaps this isn't a good idea.

**Comment by vadimdemedes** [comment]
What would happen to `onLoadStart` kind of events that should be converted to `loadstart`? We'd need to maintain a whitelist of events from https://developer.mozilla.org/en-US/docs/Web/Events and only convert camelCase to dashes if event name is not in there?

**Comment by fregante** [comment]
True, as I mentioned in my last paragraph. 

Also this seems to be [valid](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DwQwBA9gdgTgpgWwgFzgWgJZQA4FdloDOuAxiXIYQLwDeJ0hEANnAHRMQDmAvgPQB8QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.8.0&externalPlugins=), albeit ugly:

```jsx
<a onremote-input-success={console.log}/>

// Becomes

React.createElement("a", {
  "onremote-input-success": console.log
});
```

**Comment by vadimdemedes** [comment]
> Any improvements possible? Perhaps on-remote-input-success can be added as an remote-input-success event instead of -remote-input-success?

That sounds like a good compromise indeed.
