### ISSUE TITLE
Events at children not working

### ISSUE THREAD

**Issue by thiamsantos** [vadimdemedes/dom-chef#6]
First of all, thanks for the incredible work here!

In my test seems like the events are not attached to child elements.

```js
import {h} from 'dom-chef'

function handleClick() {
  console.log('hey')
}

document.body.appendChild(
  <div>
    <div onClick={handleClick}>
      hey
    </div>
  </div>
);
```

In this example if you click on the `div` nothing happens.  Is this a bug or something that I get wrong?

**Comment by vadimdemedes** [comment]
Hey, thanks, glad you like it!

Yep, this is definitely a bug and I just pushed an update (`1.1.0`), which should fix it. Thanks for reporting!

**Comment by thiamsantos** [comment]
Thanks!!!
