### ISSUE TITLE
Pass props to child components?

### ISSUE THREAD

**Issue by wimpyprogrammer** [vadimdemedes/dom-chef#77]
I'm new to `dom-chef`, and my React instincts quickly led me to structure some components like:
```jsx
const Buttons = (props) => (
    <div>
        <button onClick={props.onClickSubmit}>Submit</button>
        <button onClick={props.onClickCancel}>Cancel</button>
    </div>
);

const App = () => (
    <div>
        <Buttons onClickSubmit={foo} onClickCancel={bar} />
    </div>
);
```

But this fails because the `props` parameter of `Buttons` is `undefined`.  After reading the docs more closely, I see now that `props` would only contain the component's `defaultProps`.

Are you interested in supporting this style?  If so, I'd be glad to attempt the PR.

**Comment by wimpyprogrammer** [comment]
Whoops sorry, looks like this duplicates #75.

**Comment by fregante** [comment]
May I ask how you found dom-chef? It's funny that 2 people asked/implemented the same thing within the same week 😸 

cc @Kir-Antipov

**Comment by wimpyprogrammer** [comment]
Haha yeah that also surprised me.  I assure you that Kir-Antipov and I are not in cahoots. 😉

I'm slowly building my first browser extension and used [`notlmn/browser-extension-template`](https://github.com/notlmn/browser-extension-template) as the starting point.  I've been looking at extensions like [`sindresorhus/refined-github`](https://github.com/sindresorhus/refined-github/) and [`sindresorhus/hide-files-on-github`](https://github.com/sindresorhus/hide-files-on-github/) for reference and first encountered `dom-chef` there.

React feels like overkill for what I'm building, and `dom-chef` seems like a great, small library so I'm giving it a whirl!

**Comment by Kir-Antipov** [comment]
The concept of simultaneous invention in work :)

It seems to me that it was just a matter of time, since passing props to component constructor doesn't contradict the idea of ​​dom-chef in any way, and it is quite expected for granted by any person who is a little familiar with React xD
